<?php namespace App\Http\Controllers\KuBo; use App\Http\Controllers\Controller; use App\Models\CommunityComment; use App\Models\CommunityNotification; use App\Models\CommunityPost; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Auth;

class CommentController extends Controller {
    public function index(CommunityPost $post): JsonResponse { $comments = CommunityComment::with(['user.empDetail','replies.user.empDetail','replies.user'])->where('post_id',$post->id)->whereNull('parent_id')->orderBy('created_at','asc')->get(); return response()->json(['comments'=>$comments->map(fn($c)=>$this->fmt($c))]); }
    public function store(Request $request, CommunityPost $post): JsonResponse { $request->validate(['comment'=>'required|string|max:1000']); $user=Auth::user(); $c=CommunityComment::create(['post_id'=>$post->id,'user_id'=>$user->empID,'comment'=>$request->comment]); $c->load('user.empDetail'); if($post->user_id!==$user->empID) CommunityNotification::create(['user_id'=>$post->user_id,'type'=>'comment','reference_id'=>$c->id,'actor_id'=>$user->empID,'message'=>$user->community_full_name.' commented on your post.']); return response()->json(['success'=>true,'comment'=>$this->fmt($c),'count'=>CommunityComment::where('post_id',$post->id)->count()]); }
    public function update(Request $r, CommunityComment $c): JsonResponse { if($c->user_id!==Auth::user()->empID) return response()->json(['success'=>false,'message'=>'Unauthorized'],403); $r->validate(['comment'=>'required|string|max:1000']); $c->update(['comment'=>$r->comment]); return response()->json(['success'=>true,'message'=>'Comment updated.']); }
    public function destroy(CommunityComment $c): JsonResponse { if($c->user_id!==Auth::user()->empID) return response()->json(['success'=>false,'message'=>'Unauthorized'],403); $pid=$c->post_id; $c->delete(); return response()->json(['success'=>true,'message'=>'Comment deleted.','count'=>CommunityComment::where('post_id',$pid)->count()]); }
    public function reply(Request $r, CommunityComment $c): JsonResponse { $r->validate(['comment'=>'required|string|max:1000']); $user=Auth::user(); $reply=CommunityComment::create(['post_id'=>$c->post_id,'user_id'=>$user->empID,'comment'=>$r->comment,'parent_id'=>$c->id]); $reply->load('user.empDetail'); if($c->user_id!==$user->empID) CommunityNotification::create(['user_id'=>$c->user_id,'type'=>'reply','reference_id'=>$reply->id,'actor_id'=>$user->empID,'message'=>$user->community_full_name.' replied to your comment.']); return response()->json(['success'=>true,'reply'=>$this->fmt($reply),'count'=>CommunityComment::where('post_id',$c->post_id)->count()]); }
    private function fmt($c): array { return ['id'=>$c->id,'parent_id'=>$c->parent_id,'comment'=>$c->comment,'created_at'=>$c->created_at->diffForHumans(),'user'=>['empID'=>$c->user->empID??'','name'=>$c->user->community_full_name,'avatar'=>$c->user->community_avatar],'replies'=>$c->relationLoaded('replies')?$c->replies->map(fn($r)=>$this->fmt($r)):[],'can_edit'=>$c->user_id===Auth::user()->empID,'can_delete'=>$c->user_id===Auth::user()->empID]; }
}